#!/usr/bin/env bash

if [ ! -d "$HOME/.config/nvim/math-snippets" ]
then
  echo "Process will symlink files from $texnotesdir/snippets"
  read -p "$HOME/.config/nvim/math-snippets does not exist. mkdir? (yN) " yn
  case $yn in
      [Yy]* ) mkdir -p $HOME/.config/nvim/math-snippets; echo "[+] $HOME/.config/nvim/math-snippets created" ;;
      * ) echo "Script terminated" ; exit 0;;
  esac
else
  echo "This operation will overwrite existing files (if any) from in the destination directory.
  origin      : latex/snippets
  destination : $HOME/.config/nvim/math-snippets"
  read -p "Overwrite? (yN) " overwrite
  case $overwrite in
    [Yy]* ) ;;
    * ) echo "Script terminated" ; exit 0 ;;
  esac
fi

if [ ! -d "$HOME/.config/nvim/pythonx/" ]
then
  echo "Process will symlink python files required for snippets"
  read -p "$HOME/.config/nvim/pythonx/ does not exist. mkdir? (yN) " yn
  case $yn in
      [Yy]* ) mkdir -p $HOME/.config/nvim/pythonx/; echo "[+] $HOME/.config/nvim/pythonx/ created" ;;
      * ) echo "Script terminated" ; exit 0;;
  esac
else
  echo "This operation will overwrite existing files (if any) from in the destination directory.
  origin      : latex/snippets
  destination : $HOME/.config/nvim/pythonx/"
  read -p "Overwrite? (yN) " overwrite
  case $overwrite in
    [Yy]* ) ;;
    * ) echo "Script terminated" ; exit 0 ;;
  esac
fi

find $(pwd -L) -type f -name "*.snippets" -exec bash -c '
for file do 
  ln -sf "$file" $HOME/.config/nvim/math-snippets
done' bash {} +

ln -sf $(pwd -L)"/math_snippet_helpers.py" $HOME/.config/nvim/pythonx/

echo "[~] symlinks with snippets established"
